export { PaginaDeInicio } from './PaginaDeInicio'
export { HeroSection } from './HeroSection'
export { EquipoSection } from './EquipoSection'
export { PropiedadCard } from './PropiedadCard'
export { GoogleMapSection } from './GoogleMapSection'
export { ServicioCard } from './ServicioCard'
export { ValorPropuestaCard } from './ValorPropuestaCard'
export { ContactoCTASection } from './ContactoCTASection'
